yuft/labels/urls.py
from django.urls import path

from yuft.labels import views

urlpatterns = [
    path('retrieve/<int:serial_number>', views.LabelRetrieveView.as_view(), name='label-retrieve'),
    path('list', views.LabelListView.as_view(), name='label-list'),
    path('create', views.LabelCreateView.as_view(), name='label-create'),
]

yuft/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.template import loader
from django.urls import path, include


def home(request):
    template = loader.get_template('home.html')
    return HttpResponse(template.render())


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('label/', include('yuft.labels.urls')),
]

yuft/labeling/models.py
from django.db import models
from django.db.models import DateTimeField
from django.utils.translation import gettext_lazy as _


class DateAwareModel(models.Model):
    created_at = DateTimeField(
        verbose_name=_("created at"),
        help_text=_("creation datetime of the object"),
        auto_now_add=True,
    )

    updated_at = DateTimeField(
        verbose_name=_("updated at"),
        help_text=_("modification datetime of the object"),
        auto_now=True,
    )

    class Meta:
        abstract = True


class Label(DateAwareModel):
    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("the `name` of the property."),
        max_length=128,
    )
    brand = models.CharField(
        verbose_name=_("brand"),
        help_text=_("the `brand` of the property."),
        max_length=128,
    )
    owner = models.CharField(
        verbose_name=_("owner"),
        help_text=_("the `owner` of the property."),
        max_length=128,
    )
    serial_number = models.BigIntegerField(
        verbose_name=_("serial number"),
        help_text=_("the `serial number` of the property."),
    )
    signature = models.TextField(
        verbose_name=_("signature"),
        help_text=_("the `signature` of the information."),
    )

yuft/labels/models.py
from django.db import models
from django.db.models import DateTimeField
from django.utils.translation import gettext_lazy as _


class DateAwareModel(models.Model):
    created_at = DateTimeField(
        verbose_name=_("created at"),
        help_text=_("creation datetime of the object"),
        auto_now_add=True,
    )

    updated_at = DateTimeField(
        verbose_name=_("updated at"),
        help_text=_("modification datetime of the object"),
        auto_now=True,
    )

    class Meta:
        abstract = True


class Label(DateAwareModel):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=128,
    )
    brand = models.CharField(
        verbose_name=_("brand"),
        max_length=128,
    )
    owner = models.CharField(
        verbose_name=_("owner"),
        max_length=128,
    )
    serial_number = models.BigIntegerField(
        verbose_name=_("serial number"),
        db_index=True,
        unique=True,
    )
    signature = models.TextField(
        verbose_name=_("signature"),
    )

yuft/labels/forms.py
from django import forms

from yuft.labels.models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        exclude = ('signature',)

yuft/labels/views.py
import logging
from rest_framework.generics import RetrieveAPIView, ListAPIView, CreateAPIView

from yuft.labels.models import Label
from yuft.labels.serializers import LabelSerializer

logger = logging.getLogger(__name__)


class LabelCreateView(CreateAPIView):
    serializer_class = LabelSerializer


class LabelRetrieveView(RetrieveAPIView):
    serializer_class = LabelSerializer
    queryset = Label.objects.all()
    lookup_field = 'serial_number'


class LabelListView(ListAPIView):
    serializer_class = LabelSerializer
    queryset = Label.objects.all()

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Yuft</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'label-create' %}">Create new label</a></li>
          <li><a href="{% url 'label-list' %}">All labels</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

templates/home.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Welcome to Yuft</h1>
    <p>A labeling system which confirms that the information of
        label originated from the signer and has not been
        altered.</p>
{% endblock %}

templates/labeling/create.html
{% extends 'base_generic.html' %}

{% block content %}

 <h1>Create new Label</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

{% endblock %}

templates/labels/create.html
{% extends 'base_generic.html' %}

{% block content %}

 <h1>Create new Label</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

{% endblock %}

templates/labels/detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Label detail</h1>
    {% if label %}
        <p>Name: <b>{{ label.name }}</b></p>
        <p>Brand: <b>{{ label.brand }}</b></p>
        <p>Owner: <b>{{ label.owner }}</b></p>
        <p>Serial number: <b>{{ label.serial_number }}</b></p>
        <p>Signature: <b>{{ label.signature }}</b></p>
        <p>last update: <b>{{ label.updated_at }}</b></p>
    {% else %}
        <p>There is no label with this id.</p>
    {% endif %}
{% endblock %}

templates/labels/list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Labels</h1>
    <ul>
        {% for label in label_list %}
            <li><a href="{% url 'label-detail' pk=label.id %}">{{ label.name }}</a> - {{ label.owner }} - {{ label.brand }} - {{ label.updated_at|date }}</li>
        {% empty %}
            <li>No labels yet.</li>
        {% endfor %}
    </ul>
{% endblock %}